ENV : development
DEBUG : False
TESTING : False
SERVER_NAME : '127.0.0.1:8081'
SECRET_KEY : 
SQLALCHEMY_DATABASE_URI : 'mysql+pymysql://root:971211@127.0.0.1:3306/mall?charset=utf8'
SQLALCHEMY_TRACK_MODIFICATIONS : False
SQLALCHEMY_ECHO : False
PROPAGATE_EXCEPTIONS : 
PRESERVE_CONTEXT_ON_EXCEPTION : 
PERMANENT_SESSION_LIFETIME : 31 days, 0:00:00
USE_X_SENDFILE : False
APPLICATION_ROOT : /
SESSION_COOKIE_NAME : session
SESSION_COOKIE_DOMAIN : 
SESSION_COOKIE_PATH : 
SESSION_COOKIE_HTTPONLY : True
SESSION_COOKIE_SECURE : False
SESSION_COOKIE_SAMESITE : 
SESSION_REFRESH_EACH_REQUEST : True
MAX_CONTENT_LENGTH : 
SEND_FILE_MAX_AGE_DEFAULT : 
TRAP_BAD_REQUEST_ERRORS : 
TRAP_HTTP_EXCEPTIONS : False
EXPLAIN_TEMPLATE_LOADING : False
PREFERRED_URL_SCHEME : http
JSON_AS_ASCII : True
JSON_SORT_KEYS : True
JSONIFY_PRETTYPRINT_REGULAR : False
JSONIFY_MIMETYPE : application/json
TEMPLATES_AUTO_RELOAD : 
MAX_COOKIE_SIZE : 4093
